### PR TITLE
Fix the code style with PSR-2

### PR DESCRIPTION
**Pull request by peter279k**
# Change log
- reopen this [PR](https://github.com/vimeo/vimeo.php/pull/116).
-  just check the PSR-2 code style.
- add required extension: ```ext-json``` and ```ext-curl```.
- using StyleCI service to check the coding style. (only check the PSR-2.)

### CODE REVIEW

**Comment by Dashron** [comment]
Thanks for this! It might take a little while for us to properly review and merge it, but it's on our roadmap.

**Comment by peter279k** [comment]
Hi @Dashron, thank you for your comment. 
If finding some issues and problems, I will answer or fix it.

**Comment by erunion** [comment]
@peter279k Can you fill out our CLA form? https://developer.vimeo.com/cla

**Comment by peter279k** [comment]
Hi @erunion, thank you for your comment.
When I visit the website, the form need to have the Digital signature.
How can I get this Digital signature? Thanks.

**Comment by erunion** [comment]
@peter279k The "Digital signature" input is just asking for your name.

**Comment by erunion** [comment]
Sorry for the bit of delay, but thanks for this!

**Comment by erunion** [comment]
StyleCI is now hooked up. https://styleci.io/repos/9654006

Thanks again!

**Pull request merged**
