### PR TITLE
Update Method of POST and PATCH

### PR DESCRIPTION
**Pull request by sithu05**

### CODE REVIEW

**Comment by erunion** [comment]
Why this change?

**Comment by sithu05** [comment]
I updated these methods:
- there is no code for POST method in `Request` function (i.e line: 280). So, we can't get the 'complete_uri' from Vimeo Api Server.

**Comment by erunion** [comment]
What version of PHP are you running? The switch statement for `POST`, `PATCH`, `PUT` and `DELETE` should all be running the same request code. 

`PUT` requests will also no longer send any data with this change.

**Comment by sithu05** [comment]
I used PHP 7.1. It didn't work for 'POST' and 'PATCH'. I used these for getToken and update embed  options.

**Comment by erunion** [comment]
Can you paste the code and flow you were doing that woulnd't work without this change? Something doesn't sound right.

**Comment by sithu05** [comment]
Yes bro. Let me check again. I think that was my mistake.

**Comment by erunion** [comment]
Thanks, no worries. I just want to make sure everything's okay. 🙂

**Comment by sithu05** [comment]
My Bad, So sorry for your time. BTW, I sent mail to u bro. Thank u your time bro 💯

**Comment by erunion** [comment]
No problem!

**Pull request closed without merging**
