### PR TITLE
Add TUS 2.0

### PR DESCRIPTION
**Pull request by mstaack**

### CODE REVIEW

**Comment by jnbn** [comment]
I suggest using it as 
`"ankitpokhrel/tus-php": "^v1.0 || ^v2.0"` for future and previous releases.

**Comment by oscarnevarezleal** [comment]
This would be great to have. I'm getting an error due `ankitpokhrel/tus-php@v1` is using a previous version of `symfony/http-foundation` that attempts to change the save handler using ini_set.  

Since PHP 7.2 they dropped the ability to change the session save handler to "user" using ini_set()

**Comment by mstaack** [comment]
@muglug do you mind having a look and merge?

or is there anyone else maintaining this library?

**Comment by apsg** [comment]
Can anyone pls take a look into this?

**Comment by jnbn** [comment]
Can you please tag a release @muglug  ?

**Comment by muglug** [comment]
Done, sorry for the wait

**Pull request merged**
