### PR TITLE
Add license information to classes and the README.

### PR DESCRIPTION
**Pull request by vinkla**
Added license to every class and to the README. Also moved the namespace down. This is recommended by the [PHP FIG](http://www.php-fig.org/psr/psr-2/). This way you only need to update the LICENSE file instead of all classes.

### CODE REVIEW

**Comment by Dashron** [comment]
Apache recommends we keep that boilerplate code with their license: http://choosealicense.com/licenses/apache-2.0/ (at the bottom under the "APPENDIX: How to apply the Apache License to your work." header)

I would like to keep those licenses, but I'm cool with the namespace change.

**Comment by vinkla** [comment]
We're still using the Apache 2.0 license within the [LICENSE](https://github.com/vimeo/vimeo.php/blob/master/LICENSE) file. In this way it will be more centralized. Instead of updating the license in three different places we now only have to update the LICENSE file.

**Comment by Dashron** [comment]
I understand the engineering reasoning, and agree with it from an engineering standpoint, but I find it more important to adhere strictly to apache's recommended technique for using their license.

**Comment by vinkla** [comment]
Okay, I understand. I'll close this. The namespace change will be implemented in #61 instead.

**Pull request closed without merging**
