### PR TITLE
Fixed a couple of namespace gremlins

### PR DESCRIPTION
**Pull request by Spudley**
Hi. I have been code reviewing this library ahead of using it.

I am supplying a small patch that fixes a couple of namespace issues.

I had hoped to write some unit tests for the class as well, but I feel that it needs some refactoring in order to make it properly unit testable. I don't have time for that, so I am going to defer that for now. But I thought you might find these namespace fixes helpful anyway in the meanwhile.

### CODE REVIEW

**Comment by Dashron** [comment]
Looks great. Can you submit this to our CLA: https://developer.vimeo.com/cla and we can get it merged!

**Comment by Spudley** [comment]
Hi. Forgive me for being naive, but on the CLA form, what kind of digital signature are you looking for?

**Comment by Dashron** [comment]
Your name is fine!

**Comment by Spudley** [comment]
Hi. Thanks for that. I thought it would be something obvious like that but I wasn't sure.

I have now completed the CLA and submitted the url of this pull request on the subsequent page.

**Comment by erunion** [comment]
Tagged to [1.2.5](https://packagist.org/packages/vimeo/vimeo-api). Thanks for the fix!

**Pull request merged**
