### PR TITLE
Removed config.json and .DS_Store from the ignore file.

### PR DESCRIPTION
**Pull request by vinkla**
Also added composer.lock file. .DS_Store should be ignored globally on the system level.

### CODE REVIEW

**Comment by Dashron** [comment]
config.json is blocked for the examples (https://github.com/vimeo/vimeo.php/tree/master/example) so we shouldn't leave that out.

We can specify `examples/config.json` though, and all the rest of your changes

**Comment by vinkla** [comment]
What about if I add a second gitignore file withing the example directory? Since the `config.json` files doesn't have anything to do with the package core.

**Comment by Dashron** [comment]
Sounds good

**Comment by vinkla** [comment]
Done.

**Pull request merged**
