### PR TITLE
Updates to composer file.

### PR DESCRIPTION
**Pull request by vinkla**
Added prefer-stable and removed homepage since it already links back to this repository automagically. Also added branch alias which will allow developers to fetch the master branch by specifying the version `2.0.*@dev` instead of `dev-master` this is just good practice.

### CODE REVIEW

**Comment by Dashron** [comment]
Looks good, but I want one of the api devs to test the namespace change on a couple of different platforms before we merge it. I'll let you know when we are ready.

**Comment by vinkla** [comment]
Okay. Though, this should work as before. I've just moved it to the left side since its good practice.

**Comment by vinkla** [comment]
Any update on this?

**Comment by vinkla** [comment]
Any update on this?

**Comment by Dashron** [comment]
Still on our roadmap, but I can not currently give an estimate.

**Comment by vinkla** [comment]
:+1:

**Pull request closed without merging**
